version: "3"

tasks:
  build:
    desc: Build the project
    cmds:
      - mkdir -p bin
      - go build -o bin/chatty cmd/chatty/main.go

  # copy the binary to the /usr/local/bin directory
  install:
    desc: Install the binary to /usr/local/bin
    deps: [build]
    cmds:
      - sudo cp bin/chatty /usr/local/bin

  # remove the binary from /usr/local/bin
  uninstall:
    desc: Remove the binary from /usr/local/bin and clean up the config files and chat history
    cmds:
      - sudo rm -f /usr/local/bin/chatty
      - rm -rf ~/.chatty

  test:
    desc: Run tests
    cmds:
      - go test ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin

  default:
    desc: Run build and test tasks
    deps: [build, test]

  # New task to run directly from bin directory
  run-local:
    desc: Run the chatty binary directly from bin directory
    deps: [build]
    cmds:
      - chatty init
      - chatty "Hey, sup?"

  # New task to run conversation directly from bin directory
  run-local-conv:
    desc: Run a conversation directly from bin directory
    deps: [build]
    cmds:
      - chatty init
      - chatty --converse tux,ada --starter "Answer only with 3 words during the whole conversation"

  # New task to run auto conversation directly from bin directory
  run-local-auto:
    desc: Run an auto conversation directly from bin directory
    deps: [build]
    cmds:
      - chatty init
      - chatty --converse tux,ada,einstein --starter "Lets talk about flying elephants" --auto

  # New task to run with debug flags directly from bin directory
  debug-local:
    desc: Run the chatty binary with debug flags directly from bin directory
    deps: [build]
    cmds:
      - chatty init
      - chatty "Hey, sup?" --debug

  # New task to run conversation with debug flags directly from bin directory
  debug-local-conv:
    desc: Run a conversation with debug flags directly from bin directory
    deps: [build]
    cmds:
      - chatty init
      - chatty --converse tux,ada --starter "Answer only with 3 words during the whole conversation" --debug

  # New task to run auto conversation with debug flags directly from bin directory
  debug-local-auto:
    desc: Run an auto conversation with debug flags directly from bin directory
    deps: [build]
    cmds:
      - chatty init
      - chatty --converse tux,ada,einstein --starter "Lets talk about flying elephants" --auto --debug

  # New task to run with random agents directly from bin directory
  run-local-random:
    desc: Run with random agents directly from bin directory
    deps: [build]
    cmds:
      - chatty init
      - chatty --converse-random 3 --starter "Brainstorm an AI-based business idea" --auto

  # New task to run with 15 agents directly from bin directory
  run-local-auto-15:
    desc: Run with 15 agents directly from bin directory
    deps: [build]
    cmds:
      - chatty init
      - chatty --converse aristotle,zeus,asimov,beethoven,cleopatra,dracula,einstein,gandalf,marx,turing,kafka,feynman,newton,plato,tesla --starter "Plan the world domination through the internet" --auto

  restart:
    desc: Rebuild, reinstall, and initialize chatty
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init

  run:
    desc: Rebuild, reinstall, and run chatty with a simple message
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty "Hey, sup?"

  run-conv:
    desc: Rebuild, reinstall, and run chatty in conversation mode
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty --converse tux,ada --starter "Answer only with 3 words during the whole conversation"

  run-auto:
    desc: Rebuild, reinstall, and run chatty in auto conversation mode
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty --converse tux,ada,einstein --starter "Lets talk about flying elephants" --auto

  run-auto-15:
    desc: Rebuild, reinstall, and run chatty with 15 agents in auto conversation mode
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty --converse aristotle,zeus,asimov,beethoven,cleopatra,dracula,einstein,gandalf,marx,turing,kafka,feynman,newton,plato,tesla --starter "Plan the world domination through the internet" --auto

  run-random:
    desc: Rebuild, reinstall, and run chatty with random agents in auto conversation mode
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty --converse-random 3 --starter "Brainstorm an AI-based business idea" --auto

  debug:
    desc: Rebuild, reinstall, and run chatty with debug flags
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty "Hey, sup?" --debug

  debug-conv:
    desc: Rebuild, reinstall, and run chatty in conversation mode with debug flags
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty --converse tux,ada --starter "Answer only with 3 words during the whole conversation" --debug

  debug-auto:
    desc: Rebuild, reinstall, and run chatty in auto conversation mode with debug flags
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty --converse tux,ada,einstein --starter "Lets talk about flying elephants" --auto --debug
