version: "3"

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -o bin/chatty cmd/chatty/main.go

  # copy the binary to the /usr/local/bin directory
  install:
    desc: Install the binary to /usr/local/bin
    cmds:
      - sudo cp bin/chatty /usr/local/bin

  # remove the binary from /usr/local/bin
  uninstall:
    desc: Remove the binary from /usr/local/bin and clean up the config files and chat history
    cmds:
      - sudo rm -f /usr/local/bin/chatty
      - rm -rf ~/.chatty

  test:
    desc: Run tests
    cmds:
      - go test ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin

  default:
    desc: Run build and test tasks
    deps: [build, test]

  debug:
    desc: Run the chatty binary in debug mode
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty "Hey, sup?" --debug

  debug-conv:
    desc: Run the chatty binary in debug mode
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty --converse tux,ada --starter "Answer only with 3 words during the whole conversation" --debug

  debug-auto:
    desc: Run the chatty binary in debug mode
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty --converse tux,ada,einstein --starter "Answer only with 3 words during the whole conversation" --auto --debug
