version: "3"

tasks:
  build:
    desc: Build the project
    cmds:
      - mkdir -p bin
      - go build -o bin/chatty cmd/chatty/main.go

  install:
    desc: Install the binary to /usr/local/bin
    deps: [build]
    cmds:
      - sudo cp bin/chatty /usr/local/bin

  uninstall:
    desc: Remove the binary from /usr/local/bin and clean up the config files and chat history
    cmds:
      - sudo rm -f /usr/local/bin/chatty
      - rm -rf ~/.chatty

  test:
    desc: Run tests
    cmds:
      - go test ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin

  default:
    desc: Run build and test tasks
    deps: [build, test]

  restart:
    desc: Rebuild, reinstall, and initialize chatty
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init

  restart-config:
    desc: Rebuild, reinstall, and initialize chatty with a new config file
    cmds:
      - task restart
      - task setup-config

  setup-config:
    desc: Setup the config file
    cmds:
      - cp config.sample.json ~/.chatty/config.json

  run:
    desc: Rebuild, reinstall, and run chatty with a simple message
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty "Hey, sup?"

  run-conv:
    desc: Rebuild, reinstall, and run chatty in conversation mode
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty --converse tux,ada --starter "Answer only with 3 words during the whole conversation"

  run-auto:
    desc: Rebuild, reinstall, and run chatty in auto conversation mode
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty --converse tux,ada,einstein --starter "Lets talk about flying elephants" --auto

  run-auto-15:
    desc: Rebuild, reinstall, and run chatty with 15 agents in auto conversation mode
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty --converse aristotle,zeus,asimov,beethoven,cleopatra,dracula,einstein,gandalf,marx,turing,kafka,feynman,newton,plato,tesla --starter "Plan the world domination through the internet" --auto

  run-random:
    desc: Rebuild, reinstall, and run chatty with random agents in auto conversation mode
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty --converse-random 3 --starter "Brainstorm an AI-based business idea" --auto

  debug:
    desc: Rebuild, reinstall, and run chatty with debug flags
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty "Hey, sup?" --debug

  debug-conv:
    desc: Rebuild, reinstall, and run chatty in conversation mode with debug flags
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty --converse tux,ada --starter "Answer only with 3 words during the whole conversation" --debug

  debug-auto:
    desc: Rebuild, reinstall, and run chatty in auto conversation mode with debug flags
    cmds:
      - task uninstall
      - task build
      - task install
      - chatty init
      - chatty --converse tux,ada,einstein --starter "Lets talk about flying elephants" --auto --debug
